### PR TITLE
Moves getting started to top of index and adds Open Source blurb.

### PR DESCRIPTION
**Pull request by davidbruce**
First piece from #58.

I'm probably just wait to make the next PR until this one is merged.

### CODE REVIEW

**Review by marc0der — APPROVED** [review]
LGTM!

**Comment by marc0der** [comment]
That's great stuff, thanks @davidbruce!

**Comment by marc0der** [comment]
Just deployed it to the website, it looks great!

**Comment by davidbruce** [comment]
Awesome!  I'll have the next PR ready for you in the next day or two. :)

**Comment by marc0der** [comment]
Thanks!

**Pull request merged**
