### PR TITLE
Move getting started section to center of page. Replaces old section with open source blurb.

### PR DESCRIPTION
**Pull request by davidbruce**
This is a follow up PR for #56. I was unfortunately unable to test these changes locally since the docker image does not run on Mac M1.  

@marc0der Please take a look.

### CODE REVIEW

**Comment by marc0der** [comment]
Hi @davidbruce, this is awesome. You don't actually need to have mongo running, this is only for the (SDKs)[https://sdkman.io/sdks] page to render all its entries.

A simple `./sbt run` should do the trick for what you want to validate. The service will start on localhost:9000.

**Comment by davidbruce** [comment]
After some trial and error I got it running. Thankfully there is now sbt 1.6.0-M1 preview, but then I started running into some weird stack errors.  Apparently Play Framework **requires** between JDK 8-11 otherwise you get `java.lang.IllegalStateException: Unable to load cache item` as an error.

Beyond the initial change, I removed the hard coded `$` from all of the `<code>` tags.  I was then able to to replace it with CSS using `::before`.  This allows users to easily highlight and copy examples without having to worry about copying the `$`. I also fixed a lot of formatting of the `<pre>` tags in `usage.scala.index`.

Here are the screenshots of it running locally:
Screen Shot 2021-11-28 at 10 45 42 PM

Lastly, I fixed the footer to show Apache 2.0 instead of Apache 2.
Screen Shot 2021-11-28 at 9 39 46 PM


@marc0der Any thoughts or suggestions?

**Comment by marc0der** [comment]
Hi @davidbruce, thank you, this is fantastic work. Heaven only knows that I suck at web development so good of you to do the tweaks. Everything you did looks great!

The versions of Play and sbt we currently use only works with Java 8-11 as you pointed out. I'll make mention of that in the README.md.

I'll be releasing this later in the week.

**Comment by marc0der** [comment]
@davidbruce Apologies for not releasing this. I've found several problems with this PR. We have code blocks that don't start with a `$` (the config block at the end of the usage page).  They now all have a floating `$` at the beginning. If you could release a patch, I'd be very grateful.

**Comment by davidbruce** [comment]
@marc0der No problem, I'll take a look in a few hours and get it fixed.  Sorry about not catching that!

**Comment by marc0der** [comment]
@davidbruce No worries, and thanks again!

**Pull request merged**
