### PR TITLE
restyling proposition

### PR DESCRIPTION
**Pull request by SvMak**
Hello. I would like to suggest a small restyling of the site to freshen it up and make it a bit more modern, would appreciate feedback.

Thanks.

### CODE REVIEW

**Comment by marc0der** [comment]
Hey @SvMak,

Firstly, I just want to say that I'm completely blown away by your awesome work and that I simply love, love, love it! Thanks so much for all the effort you've put into this. I can't thank you enough.

If you don't mind, I have one or two tiny tweaks that would ask, but overall, the effect is fantastic. Shall we take it offline on the community Slack?

Cheers,
Marco.

**Comment by SvMak** [comment]
Hello, thank you!
Of course you can make suggestions for changes.

**Comment by hgeraldino** [comment]
For what is worth, I left this comment on the slack channel, let me know what you think:

```
looks pretty cool.. I think the only thing I’d change is probably the contributors section, which occupies >50% of the landing page

maybe a carousel/slider (with a link to a page that shows the full list of contributors would be better?
```

**Comment by marc0der** [comment]
This is all looking great, thank you. I also noticed that the contributors don't link to their corresponding open collective pages. Is that something that we can do?

Another thing was that the carbon ad is taking up an entire row and is off to the right side. I'm wondering if we can move it up to the spot where it was in the top right corner where it felt more out of the way. This isn't super important though.

**Comment by SvMak** [comment]
You can check fixes. If you have other suggestions, let me know.

**Comment by marc0der** [comment]
This is fantastic. And again, thank you so much for everything. It looks great.

**Pull request merged**
